run:
  timeout: 10m

linters-settings:
  misspell:
    locale: US

linters:
  disable-all: true
  enable:
    # defaults
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    # extra
    - bodyclose
    - containedctx
    - contextcheck
    - copyloopvar
    - dogsled
    - durationcheck
    - gofmt
    - goimports
    - loggercheck
    - misspell
    - nilerr
    - nilnil
    - nosprintfhostport
    - prealloc
    - predeclared
    - reassign
    - revive
    - unconvert
    - unparam
    - wastedassign
    - whitespace
    - wsl
